site_name: Scoutr
site_author: GE Skunkworks
repo_url: https://github.com/GESkunkworks/scoutr
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

nav:
  - index.md
  - setup.md
  - endpoint-structure.md
  - access-control.md
  - filtering.md
  - validation.md
  - errors-and-metrics.md
  - example.md

plugins:
  - search

markdown_extensions:
  - codehilite:
